import type { Service } from "./types";

export const code: Service[] = [
  { id: "github", name: "GitHub", category: "code", templates: [{ url: "https://github.com/{id}" }] },
  { id: "gist", name: "GitHub Gist", category: "code", templates: [{ url: "https://gist.github.com/{id}" }] },
  { id: "gitlab", name: "GitLab", category: "code", templates: [{ url: "https://gitlab.com/{id}" }], check: "https://gitlab.com/api/v4/users?username={id}", found: ["[{"] },
  { id: "bitbucket", name: "Bitbucket", category: "code", templates: [{ url: "https://bitbucket.org/{id}" }] },
  { id: "codepen", name: "CodePen", category: "code", templates: [{ url: "https://codepen.io/{id}" }] },
  { id: "jsfiddle", name: "JSFiddle", category: "code", templates: [{ url: "https://jsfiddle.net/{id}" }], notFound: ["that page does not exist"] },
  { id: "replit", name: "Replit", category: "code", templates: [{ url: "https://replit.com/@{id}" }] },
  { id: "stackblitz", name: "StackBlitz", category: "code", templates: [{ url: "https://stackblitz.com/edit/{id}" }] },
  { id: "codesandbox", name: "CodeSandbox", category: "code", templates: [{ url: "https://codesandbox.io/s/{id}" }] },
  { id: "glitch", name: "Glitch", category: "code", templates: [{ url: "https://glitch.com/~{id}" }] },
  { id: "hackmd", name: "HackMD", category: "code", templates: [{ url: "https://hackmd.io/{id}" }] },
  { id: "ideone", name: "Ideone", category: "code", templates: [{ url: "https://ideone.com/{id}" }] },
  { id: "codeberg", name: "Codeberg", category: "code", templates: [{ url: "https://codeberg.org/{id}" }] },
  { id: "sourceforge", name: "SourceForge", category: "code", templates: [{ url: "https://sourceforge.net/projects/{id}" }] },
  { id: "gitlab_snippet", name: "GitLab Snippet", category: "code", templates: [{ url: "https://gitlab.com/-/snippets/{id}" }] },
  { id: "npm", name: "npm", category: "code", templates: [{ url: "https://www.npmjs.com/package/{id}" }], check: "https://registry.npmjs.org/{id}" },
  { id: "rubygems", name: "RubyGems", category: "code", templates: [{ url: "https://rubygems.org/gems/{id}" }] },
  { id: "nuget", name: "NuGet", category: "code", templates: [{ url: "https://www.nuget.org/packages/{id}" }] },
  { id: "dockerhub", name: "Docker Hub", category: "code", templates: [{ url: "https://hub.docker.com/r/{id}" }] },
  { id: "bitbucket_snippet", name: "Bitbucket Snippet", category: "code", templates: [{ url: "https://bitbucket.org/snippets/{id}" }] },
  { id: "observable", name: "Observable", category: "code", templates: [{ url: "https://observablehq.com/@{id}" }] },
  { id: "huggingface", name: "Hugging Face", category: "code", templates: [{ url: "https://huggingface.co/{id}" }] },
  { id: "packagist", name: "Packagist", category: "code", templates: [{ url: "https://packagist.org/packages/{id}" }], notFound: ["packagist.org/search"] },
  { id: "snapcraft", name: "Snapcraft", category: "code", templates: [{ url: "https://snapcraft.io/{id}" }] },
  { id: "fdroid", name: "F-Droid", category: "code", templates: [{ url: "https://f-droid.org/packages/{id}" }] },
  { id: "chromestore", name: "Chrome Web Store", category: "code", templates: [{ url: "https://chromewebstore.google.com/detail/{id}" }] },
  { id: "firefoxaddon", name: "Firefox Add-ons", category: "code", templates: [{ url: "https://addons.mozilla.org/en-US/firefox/addon/{id}" }] },
  { id: "jetbrains", name: "JetBrains Plugins", category: "code", templates: [{ url: "https://plugins.jetbrains.com/plugin/{id}" }] },
  { id: "pypi", name: "PyPI", category: "code", templates: [{ url: "https://pypi.org/project/{id}" }], check: "https://pypi.org/pypi/{id}/json" },
  { id: "crates", name: "crates.io", category: "code", templates: [{ url: "https://crates.io/crates/{id}" }], check: "https://crates.io/api/v1/crates/{id}" },
  { id: "kaggle", name: "Kaggle", category: "code", templates: [{ url: "https://www.kaggle.com/{id}" }], verify: false },
];
