import type { Service } from "./types";

export const people: Service[] = [
  { id: "wm_aboutme", name: "about.me", category: "social", templates: [{ url: "https://about.me/{id}" }], notFound: ["<title>about.me</title>"] },
  { id: "wm_foursquare", name: "Foursquare", category: "social", templates: [{ url: "https://foursquare.com/{id}" }] },
  { id: "wm_letterboxd", name: "Letterboxd", category: "social", templates: [{ url: "https://letterboxd.com/{id}/" }], notFound: ["sorry, we can’t find the page you’ve requested."] },
  { id: "wm_minds", name: "Minds", category: "social", templates: [{ url: "https://www.minds.com/api/v3/register/validate?username={id}" }], notFound: ["\"valid\":true"] },
  { id: "wm_myspace", name: "MySpace", category: "social", templates: [{ url: "https://myspace.com/{id}" }], notFound: ["<!-- 404 -->"] },
  { id: "wm_openstreetmap", name: "OpenStreetMap", category: "social", templates: [{ url: "https://www.openstreetmap.org/user/{id}" }], notFound: ["does not exist"] },
  { id: "wm_plurk", name: "Plurk", category: "social", templates: [{ url: "https://www.plurk.com/{id}" }], notFound: ["register your plurk account"] },
  { id: "wm_slideshare", name: "Slideshare", category: "social", templates: [{ url: "https://www.slideshare.net/{id}" }], verify: false },
  { id: "wm_speakerdeck", name: "Speaker Deck", category: "social", templates: [{ url: "https://speakerdeck.com/{id}/" }], notFound: ["user not found - speaker deck"] },
  { id: "wm_strava", name: "Strava", category: "social", templates: [{ url: "https://www.strava.com/athletes/{id}" }], notFound: ["\"page\":\"/404\""] },
  { id: "wm_untappd", name: "Untappd", category: "social", templates: [{ url: "https://untappd.com/user/{id}/" }], notFound: ["class=\"search_404\""] },
  { id: "wm_vsco", name: "vsco", category: "social", templates: [{ url: "https://vsco.co/{id}/gallery" }], notFound: ["\"error\":\"site_not_found\"}"] },
  { id: "wm_wattpad", name: "Wattpad", category: "social", templates: [{ url: "https://www.wattpad.com/api/v3/users/{id}" }], notFound: ["\"error_code\":"] },
  { id: "wm_xing", name: "Xing", category: "social", templates: [{ url: "https://www.xing.com/profile/{id}" }], browser: true, notFound: ["404 - not found"] },
  { id: "wm_disqus", name: "Disqus", category: "social", templates: [{ url: "https://disqus.com/api/3.0/users/details?user=username:{id}&api_key=E8Uh5l5fHZ6gD8U3KycjAIAk46f68Zw7C6eW8WSjZvCLXebZ7p0r1yrYDrLilk2F" }], notFound: ["\"code\":2"] },
  { id: "wm_tellonym", name: "Tellonym", category: "social", templates: [{ url: "https://api.tellonym.me/profiles/name/{id}" }], notFound: ["\"code\":\"not_found\""] },
  { id: "wm_hackernews", name: "Hacker News", category: "code", templates: [{ url: "https://hacker-news.firebaseio.com/v0/user/{id}.json?print=pretty" }], notFound: ["null"] },
  { id: "wm_hackerrank", name: "HackerRank", category: "code", templates: [{ url: "https://www.hackerrank.com/rest/contests/master/hackers/{id}/profile" }], notFound: ["\"error\":\"not found\""] },
  { id: "wm_hackerearth", name: "hackerearth", category: "code", templates: [{ url: "https://www.hackerearth.com/@{id}" }], notFound: ["404 | hackerearth"] },
  { id: "wm_codeforces", name: "Codeforces", category: "code", templates: [{ url: "https://codeforces.com/api/user.info?handles={id}" }], notFound: ["\"status\":\"failed\""] },
  { id: "wm_codechef", name: "CodeChef", category: "code", templates: [{ url: "https://www.codechef.com/users/{id}" }] },
  { id: "wm_freecodecamp", name: "freeCodeCamp", category: "code", templates: [{ url: "https://api.freecodecamp.org/users/get-public-profile?username={id}" }], notFound: ["{}"] },
  { id: "wm_geeksforgeeks", name: "GeeksForGeeks", category: "code", templates: [{ url: "https://authapi.geeksforgeeks.org/api-get/user-profile-info/?handle={id}" }], notFound: ["\"message\":\"user not found!\""] },
  { id: "wm_gitea", name: "Gitea", category: "code", templates: [{ url: "https://gitea.com/api/v1/users/{id}" }], notFound: ["\"message\":\"user redirect does not exist"] },
  { id: "wm_gitee", name: "Gitee", category: "code", templates: [{ url: "https://gitee.com/{id}" }], notFound: ["class=\"container error midcenter\""] },
  { id: "wm_figma", name: "Figma", category: "code", browser: true, templates: [{ url: "https://www.figma.com/api/profile/handle/{id}" }], notFound: ["\"status\":404"] },
  { id: "wm_tryhackme", name: "TryHackMe", category: "code", templates: [{ url: "https://tryhackme.com/api/user/exist/{id}" }], notFound: ["\"success\":false"] },
  { id: "wm_bugcrowd", name: "Bugcrowd", category: "code", templates: [{ url: "https://bugcrowd.com/profile-service/v1/profiles/{id}" }], notFound: ["\"error\":\"not found\""] },
  { id: "wm_asciinema", name: "asciinema", category: "code", templates: [{ url: "https://asciinema.org/~{id}" }], notFound: ["<h1>404 not found</h1>"] },
  { id: "wm_wakatime", name: "Wakatime", category: "code", templates: [{ url: "https://wakatime.com/api/v1/users/{id}" }], notFound: ["\"error\": \"not found.\""] },
  { id: "wm_devrant", name: "devRant", category: "code", templates: [{ url: "https://devrant.com/api/get-user-id?app=3&username={id}" }], notFound: ["\"success\":false"] },
  { id: "wm_atcoder", name: "AtCoder", category: "code", templates: [{ url: "https://atcoder.jp/users/{id}" }], notFound: [">404 page not found</h1>"] },
  { id: "wm_virustotal", name: "VirusTotal", category: "code", templates: [{ url: "https://www.virustotal.com/ui/users/{id}" }], notFound: ["\"code\": \"notfounderror\""] },
  { id: "wm_chocolatey", name: "Chocolatey", category: "code", templates: [{ url: "https://community.chocolatey.org/profiles/{id}" }], notFound: ["id=\"error404message\""] },
  { id: "wm_chesscom", name: "Chess.com", category: "social", templates: [{ url: "https://api.chess.com/pub/player/{id}" }], notFound: ["\"code\":0"] },
  { id: "wm_lichessorg", name: "lichess.org", category: "social", templates: [{ url: "https://lichess.org/api/player/autocomplete?term={id}&exists=1" }], notFound: ["false"] },
  { id: "wm_xboxgamertag", name: "Xbox Gamertag", category: "social", templates: [{ url: "https://www.xboxgamertag.com/search/{id}" }], notFound: ["gamertag doesn't exist"] },
  { id: "wm_playstationnetwork", name: "Playstation Network", category: "social", templates: [{ url: "https://psnprofiles.com/xhr/search/users?q={id}" }], notFound: ["we couldn't find anything "] },
  { id: "wm_gog", name: "GOG", category: "social", templates: [{ url: "https://www.gog.com/u/{id}" }], notFound: ["href=\"http://www.gog.com/404\""] },
  { id: "wm_kongregate", name: "Kongregate", category: "social", templates: [{ url: "https://www.kongregate.com/accounts/{id}" }], notFound: ["sorry, no account with that name was found"] },
  { id: "wm_boardgamegeek", name: "BoardGameGeek", category: "social", templates: [{ url: "https://api.geekdo.com/api/accounts/validate/username?username={id}" }], found: ["already taken"] },
  { id: "wm_speedrun", name: "speedrun", category: "social", templates: [{ url: "https://www.speedrun.com/user/{id}/" }], notFound: ["<title>speedrun.com"] },
  { id: "wm_opgg", name: "OPGG", category: "social", templates: [{ url: "https://eune.op.gg/summoners/eune/{id}" }], notFound: ["guide - op.gg"] },
  { id: "wm_moxfield", name: "Moxfield", category: "social", templates: [{ url: "https://api2.moxfield.com/v1/users/{id}" }], notFound: ["\"status\":404"] },
  { id: "wm_duolingo", name: "Duolingo", category: "other", templates: [{ url: "https://www.duolingo.com/2017-06-30/users?username={id}&_=1628308619574" }], notFound: ["\"users\":[]"] },
  { id: "wm_quizlet", name: "Quizlet", category: "other", templates: [{ url: "https://quizlet.com/webapi/3.2/users/check-username?username={id}" }], notFound: ["\"success\":true"] },
  { id: "wm_librarything", name: "LibraryThing", category: "other", templates: [{ url: "https://www.librarything.com/profile/{id}" }], notFound: ["error: this user doesn't exist"] },
  { id: "wm_metacritic", name: "Metacritic", category: "other", templates: [{ url: "https://www.metacritic.com/user/{id}/" }], notFound: ["class=\"c-error404\""] },
  { id: "wm_instructables", name: "Instructables", category: "other", templates: [{ url: "https://www.instructables.com/json-api/showAuthorExists?screenName={id}" }], notFound: ["\"error\": \"sorry, we couldn't find that one!\""] },
  { id: "wm_houzz", name: "Houzz", category: "other", templates: [{ url: "https://www.houzz.com/user/{id}" }], verify: false },
  { id: "wm_ultimateguitar", name: "Ultimate Guitar", category: "other", templates: [{ url: "https://www.ultimate-guitar.com/u/{id}" }], notFound: ["oops! we couldn't find that page."] },
  { id: "wm_pinkbike", name: "PinkBike", category: "other", templates: [{ url: "https://www.pinkbike.com/u/{id}/" }], notFound: ["i couldn't find the page you were looking for"] },
  { id: "wm_inaturalist", name: "inaturalist", category: "other", templates: [{ url: "https://api.inaturalist.org/v1/users/{id}" }], notFound: ["\"status\":404"] },
  { id: "wm_ebay", name: "eBay", category: "market", browser: true, templates: [{ url: "https://www.ebay.com/usr/{id}" }], notFound: ["was not found"] },
  { id: "wm_depop", name: "depop", category: "market", templates: [{ url: "https://www.depop.com/{id}/" }], notFound: ["sorry, that page doesn't exist"] },
  { id: "wm_poshmark", name: "Poshmark", category: "market", templates: [{ url: "https://poshmark.com/closet/{id}" }], notFound: ["page not found - poshmark"] },
  { id: "wm_kickstarter", name: "Kickstarter", category: "market", templates: [{ url: "https://www.kickstarter.com/profile/{id}" }], notFound: ["oops, something went missing"] },
  { id: "wm_redbubble", name: "redbubble", category: "market", templates: [{ url: "https://www.redbubble.com/people/{id}/shop" }], notFound: ["this is a lost cause."] },
  { id: "wm_cameo", name: "Cameo", category: "market", templates: [{ url: "https://www.cameo.com/api/v2/users/{id}" }], notFound: ["\"message\":\"we could not find the user:"] },
  { id: "wm_paypal", name: "Paypal", category: "market", templates: [{ url: "https://www.paypal.com/paypalme/{id}" }], notFound: ["<title>paypal.me</title><meta"] },
  { id: "wm_venmo", name: "Venmo", category: "market", templates: [{ url: "https://account.venmo.com/u/{id}" }], notFound: ["sorry, the page you requested does not exist!"] },
  { id: "wm_tradingview", name: "tradingview", category: "market", templates: [{ url: "https://www.tradingview.com/u/{id}/" }], notFound: ["page not found — tradingview"] },
  { id: "wm_etoro", name: "Etoro", category: "market", templates: [{ url: "https://www.etoro.com/api/logininfo/v1.1/users/{id}" }], notFound: ["\"errorcode\":\"notfound\""] },
  { id: "wm_liberapay", name: "Liberapay", category: "market", templates: [{ url: "https://liberapay.com/{id}" }], notFound: ["response code: 404"] },
  { id: "wm_opencollective", name: "Opencollective", category: "market", templates: [{ url: "https://opencollective.com/{id}" }], notFound: ["not found"] },
  { id: "wm_streamelements", name: "StreamElements", category: "market", templates: [{ url: "https://api.streamelements.com/kappa/v2/channels/{id}" }], notFound: ["error"] },
  { id: "wm_streamlabs", name: "StreamLabs", category: "market", templates: [{ url: "https://streamlabs.com/api/v6/user/{id}" }], notFound: ["<title>unauthorized</title>"] },
  { id: "wm_discogs", name: "Discogs", category: "music", templates: [{ url: "https://api.discogs.com/users/{id}" }], notFound: ["\"message\": \"user does not exist or may have been deleted.\""] },
  { id: "wm_bandlab", name: "Bandlab", category: "music", templates: [{ url: "https://www.bandlab.com/api/v1.3/users/{id}" }], notFound: ["couldn’t find any matching element, it might be deleted"] },
  { id: "wm_freesound", name: "freesound", category: "music", templates: [{ url: "https://freesound.org/people/{id}/section/stats/?ajax=1" }], notFound: ["<h1>page not found</h1>"] },
  { id: "wm_setlistfm", name: "setlist.fm", category: "music", templates: [{ url: "https://www.setlist.fm/user/{id}" }], notFound: ["sorry, the page you requested doesn't exist"] },
  { id: "wm_smule", name: "smule", category: "music", browser: true, templates: [{ url: "https://www.smule.com/api/profile/?handle={id}" }], notFound: ["\"profile_not_found\":true"] },
  { id: "wm_trakt", name: "trakt", category: "video", templates: [{ url: "https://trakt.tv/users/{id}" }], notFound: ["the page you were looking for doesn't exist (404) - trakt.tv"] },
  { id: "wm_gravatar", name: "Gravatar", category: "images", templates: [{ url: "https://en.gravatar.com/{id}.json" }], found: ["\"entry\""] },
  { id: "wm_iconfinder", name: "Iconfinder", category: "images", verify: false, templates: [{ url: "https://www.iconfinder.com/{id}" }], notFound: ["we couldn't find the page you are looking for."] },
  { id: "wm_imageshack", name: "ImageShack", category: "images", templates: [{ url: "https://imageshack.com/user/{id}" }] },
  { id: "wm_furaffinity", name: "Fur Affinity", category: "images", templates: [{ url: "https://www.furaffinity.net/user/{id}/" }], notFound: ["<h2>system error</h2>"] },
  { id: "wm_weasyl", name: "Weasyl", category: "images", templates: [{ url: "https://www.weasyl.com/~{id}" }], notFound: ["this user doesn't seem to be in our database."] },
  { id: "wm_picsart", name: "Picsart", category: "images", templates: [{ url: "https://api.picsart.com/users/show/{id}.json" }], notFound: ["\"status\":\"error\""] },
];
