import type { Service } from "./types";

export const shorteners: Service[] = [
  { id: "bitly", name: "Bitly", category: "shorteners", templates: [{ url: "https://bit.ly/{id}" }] },
  { id: "tinyurl", name: "TinyURL", category: "shorteners", templates: [{ url: "https://tinyurl.com/{id}" }] },
  { id: "googl", name: "Goo.gl", category: "shorteners", templates: [{ url: "https://goo.gl/{id}" }] },
  { id: "tinycc", name: "Tiny.cc", category: "shorteners", templates: [{ url: "https://tiny.cc/{id}" }] },
  { id: "isgd", name: "is.gd", category: "shorteners", templates: [{ url: "https://is.gd/{id}" }] },
  { id: "vgd", name: "v.gd", category: "shorteners", templates: [{ url: "https://v.gd/{id}" }] },
  { id: "cuttly", name: "Cutt.ly", category: "shorteners", templates: [{ url: "https://cutt.ly/{id}" }] },
  { id: "rbgy", name: "rb.gy", category: "shorteners", templates: [{ url: "https://rb.gy/{id}" }] },
  { id: "tly", name: "T.ly", category: "shorteners", templates: [{ url: "https://t.ly/{id}" }] },
  { id: "shorturl", name: "ShortURL", category: "shorteners", templates: [{ url: "https://shorturl.at/{id}" }], notFound: ["404 page not found"] },
  { id: "owly", name: "Ow.ly", category: "shorteners", templates: [{ url: "https://ow.ly/{id}" }], notFound: ["lost-owly"] },
  { id: "buffly", name: "Buff.ly", category: "shorteners", templates: [{ url: "https://buff.ly/{id}" }], notFound: ["buffer: social media management"] },
  { id: "rebrandly", name: "Rebrandly", category: "shorteners", templates: [{ url: "https://rebrand.ly/{id}" }], notFound: ["broken-links"] },
  { id: "bitdo", name: "Bit.do", category: "shorteners", templates: [{ url: "https://bit.do/{id}" }], dead: true },
  { id: "gggg", name: "Gg.gg", category: "shorteners", templates: [{ url: "https://gg.gg/{id}" }] },
  { id: "tco", name: "T.co", category: "shorteners", templates: [{ url: "https://t.co/{id}" }] },
  { id: "adfly", name: "Adf.ly", category: "shorteners", templates: [{ url: "https://adf.ly/{id}" }], notFound: ["adfly-notice"] },
  { id: "sniply", name: "Sniply", category: "shorteners", templates: [{ url: "https://snip.ly/{id}" }] },
  { id: "tree", name: "tr.ee", category: "shorteners", templates: [{ url: "https://tr.ee/{id}" }] },
  { id: "onedrive", name: "OneDrive", category: "shorteners", templates: [{ url: "https://1drv.ms/{id}" }] },
  { id: "lnkdin", name: "lnkd.in", category: "shorteners", templates: [{ url: "https://lnkd.in/{id}" }] },
  { id: "kutt", name: "Kutt", category: "shorteners", templates: [{ url: "https://kutt.it/{id}" }] },
  { id: "ouo", name: "Ouo.io", category: "shorteners", templates: [{ url: "https://ouo.io/{id}" }], notFound: ["link not found"] },
  { id: "adfocus", name: "AdFocus", category: "shorteners", templates: [{ url: "https://adfoc.us/{id}" }] },
  { id: "sptifi", name: "spti.fi", category: "shorteners", templates: [{ url: "https://spti.fi/{id}" }], notFound: ["dub.co/tools"] },
  { id: "gitnew", name: "git.new", category: "shorteners", templates: [{ url: "https://git.new/{id}" }], notFound: ["dub.co/tools"] },
  { id: "callink", name: "cal.link", category: "shorteners", templates: [{ url: "https://cal.link/{id}" }], notFound: ["dub.co/tools"] },
  { id: "chatgpt", name: "chatg.pt", category: "shorteners", templates: [{ url: "https://chatg.pt/{id}" }], notFound: ["dub.co/tools"] },
  { id: "figpage", name: "fig.page", category: "shorteners", templates: [{ url: "https://fig.page/{id}" }], notFound: ["dub.co/tools"] },
  { id: "ggllink", name: "ggl.link", category: "shorteners", templates: [{ url: "https://ggl.link/{id}" }], notFound: ["dub.co/tools"] },
  { id: "dubsh", name: "dub.sh", category: "shorteners", templates: [{ url: "https://dub.sh/{id}" }], verify: false },
  { id: "shortio", name: "Short.io", category: "shorteners", templates: [{ url: "https://short.io/{id}" }] },
  { id: "blink", name: "BL.INK", category: "shorteners", templates: [{ url: "https://bl.ink/{id}" }] },
  { id: "linkly", name: "Linkly", category: "shorteners", templates: [{ url: "https://linklyhq.com/{id}" }] },
  { id: "branch", name: "Branch", category: "shorteners", templates: [{ url: "https://bnc.lt/{id}" }], verify: false },
  { id: "firebase", name: "Firebase Links", category: "shorteners", templates: [{ url: "https://page.link/{id}" }], dead: true },
  { id: "amznto", name: "amzn.to", category: "shorteners", templates: [{ url: "https://amzn.to/{id}" }], verify: false },
  { id: "fbme", name: "fb.me", category: "shorteners", templates: [{ url: "https://fb.me/{id}" }], verify: false },
  { id: "instagramshort", name: "instagr.am", category: "shorteners", templates: [{ url: "https://instagr.am/{id}" }], verify: false },
  { id: "spotifylink", name: "spotify.link", category: "shorteners", templates: [{ url: "https://spotify.link/{id}" }], found: ["open.spotify.com/track", "open.spotify.com/album", "open.spotify.com/playlist", "open.spotify.com/artist", "open.spotify.com/episode", "open.spotify.com/show", "open.spotify.com/user"] },
  { id: "gitio", name: "git.io", category: "shorteners", templates: [{ url: "https://git.io/{id}" }], dead: true },
  { id: "dbtt", name: "db.tt", category: "shorteners", templates: [{ url: "https://db.tt/{id}" }], dead: true },
  { id: "wame", name: "wa.me", category: "shorteners", templates: [{ url: "https://wa.me/{id}" }], verify: false },
  { id: "zmurl", name: "zmurl.us", category: "shorteners", templates: [{ url: "https://zmurl.us/{id}" }] },
  { id: "canva", name: "canva.me", category: "shorteners", templates: [{ url: "https://canva.me/{id}" }] , found: ["_branch_match_id"] },
];
