import type { Service } from "./types";

export const social: Service[] = [
  { id: "discord", name: "Discord", category: "social", templates: [{ url: "https://discord.gg/{id}" }], notFound: ["group chat that"] },
  { id: "telegram", name: "Telegram", category: "social", templates: [{ url: "https://t.me/{id}" }], verify: false },
  { id: "whatsapp", name: "WhatsApp Group", category: "social", templates: [{ url: "https://chat.whatsapp.com/{id}" }], notFound: ['og:title" content=""'] },
  {
    id: "twitter",
    name: "Twitter",
    category: "social",
    templates: [
      { label: "twitter", url: "https://twitter.com/{id}" },
      { label: "x", url: "https://x.com/{id}" },
    ],
  },
  {
    id: "instagram",
    name: "Instagram",
    category: "social",
    templates: [
      { label: "user", url: "https://www.instagram.com/{id}" },
      { label: "post", url: "https://www.instagram.com/p/{id}" },
    ],
    verify: false,
  },
  { id: "reddit", name: "Reddit", category: "social", templates: [{ url: "https://redd.it/{id}" }], verify: false },
  { id: "facebook", name: "Facebook", category: "social", templates: [{ url: "https://www.facebook.com/{id}" }] },
  {
    id: "steam",
    name: "Steam",
    category: "social",
    templates: [
      { label: "vanity", url: "https://steamcommunity.com/id/{id}" },
      { label: "id64", url: "https://steamcommunity.com/profiles/{id}" },
    ],
    notFound: ["steam community :: error", "specified profile could not be found", "no user logged in"],
  },
  { id: "tiktok_user", name: "TikTok", category: "social", templates: [{ url: "https://www.tiktok.com/@{id}" }], verify: false },
  { id: "snapchat", name: "Snapchat", category: "social", templates: [{ url: "https://www.snapchat.com/add/{id}" }] },
  { id: "tumblr", name: "Tumblr", category: "social", templates: [{ url: "https://{id}.tumblr.com" }] },
  { id: "pinterest", name: "Pinterest", category: "social", templates: [{ url: "https://www.pinterest.com/{id}" }], notFound: ["user not found"] },
  { id: "linkedin", name: "LinkedIn", category: "social", templates: [{ url: "https://www.linkedin.com/in/{id}" }] },
  { id: "threads", name: "Threads", category: "social", templates: [{ url: "https://www.threads.net/@{id}" }], verify: false },
  { id: "bluesky", name: "Bluesky", category: "social", templates: [{ url: "https://bsky.app/profile/{id}" }], found: ["on bluesky"] },
  { id: "vk", name: "VK", category: "social", templates: [{ url: "https://vk.com/{id}" }] },
  { id: "linktree", name: "Linktree", category: "social", templates: [{ url: "https://linktr.ee/{id}" }] },
  { id: "medium", name: "Medium", category: "social", templates: [{ url: "https://medium.com/@{id}" }], notFound: ["not found"] },
  { id: "substack", name: "Substack", category: "social", templates: [{ url: "https://{id}.substack.com" }] },
  { id: "quora", name: "Quora", category: "social", templates: [{ url: "https://www.quora.com/profile/{id}" }] },
  { id: "stackoverflow", name: "Stack Overflow", category: "social", templates: [{ url: "https://stackoverflow.com/users/{id}" }], check: "https://api.stackexchange.com/2.3/users/{id}?site=stackoverflow", found: ['"items":[{'] },
  { id: "producthunt", name: "Product Hunt", category: "social", templates: [{ url: "https://www.producthunt.com/@{id}" }] },
  { id: "devto", name: "DEV", category: "social", templates: [{ url: "https://dev.to/{id}" }] },
  { id: "hashnode", name: "Hashnode", category: "social", templates: [{ url: "https://hashnode.com/@{id}" }], notFound: ["user not found"] },
  { id: "wordpress", name: "WordPress", category: "social", templates: [{ url: "https://{id}.wordpress.com" }], notFound: ["wordpress.com/typo"] },
  { id: "blogger", name: "Blogger", category: "social", templates: [{ url: "https://{id}.blogspot.com" }] },
  { id: "allmylinks", name: "AllMyLinks", category: "social", templates: [{ url: "https://allmylinks.com/{id}" }] },
  { id: "biolink", name: "Bio.link", category: "social", templates: [{ url: "https://bio.link/{id}" }] },
  { id: "carrd", name: "Carrd", category: "social", templates: [{ url: "https://{id}.carrd.co" }] },
  { id: "neocities", name: "Neocities", category: "social", templates: [{ url: "https://{id}.neocities.org" }] },
  { id: "mirror", name: "Mirror", category: "social", templates: [{ url: "https://mirror.xyz/{id}" }], verify: false },
  { id: "warpcast", name: "Warpcast", category: "social", templates: [{ url: "https://warpcast.com/{id}" }], check: "https://api.warpcast.com/v2/user-by-username?username={id}" },
  { id: "myanimelist", name: "MyAnimeList", group: "MyAnimeList", category: "social", templates: [{ label: "profile", url: "https://myanimelist.net/profile/{id}" }] },
  { id: "malanime", name: "MyAnimeList", group: "MyAnimeList", category: "social", templates: [{ label: "anime", url: "https://myanimelist.net/anime/{id}" }], numeric: true },
  { id: "malmanga", name: "MyAnimeList", group: "MyAnimeList", category: "social", templates: [{ label: "manga", url: "https://myanimelist.net/manga/{id}" }], numeric: true },
  { id: "anilist", name: "AniList", category: "social", templates: [{ url: "https://anilist.co/user/{id}" }], verify: false },
  { id: "allmanga", name: "AllManga", category: "social", templates: [{ url: "https://allmanga.to/bangumi/{id}" }], verify: false },
  { id: "fandom", name: "Fandom", category: "social", templates: [{ url: "https://{id}.fandom.com" }] },
  { id: "pinit", name: "pin.it", category: "social", templates: [{ url: "https://pin.it/{id}" }], verify: false },
  { id: "osu", name: "osu!", group: "osu!", category: "social", templates: [{ label: "profile", url: "https://osu.ppy.sh/users/{id}" }] },
  { id: "niconicouser", name: "Niconico", group: "Niconico", category: "social", templates: [{ label: "user", url: "https://www.nicovideo.jp/user/{id}" }], numeric: true },
  { id: "guilded", name: "Guilded", category: "social", templates: [{ url: "https://www.guilded.gg/{id}" }], verify: false },
  { id: "roblox", name: "Roblox", category: "social", templates: [
    { label: "game", url: "https://www.roblox.com/games/{id}" },
    { label: "user", url: "https://www.roblox.com/users/{id}/profile" },
  ], numeric: true },
];
